[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' *.datocms-assets.com; style-src 'self' fonts.googleapis.com fonts.gstatic.com; font-src 'self' fonts.gstatic.com;"
