[functions]
  directory = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: www.datocms-assets.com; style-src 'self' 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/projects/private/*"
  status = 200
  force = true
  conditions = {Role = ["pvt"]}

[[redirects]]
  from = "/projects/private/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
