[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://www.datocms-assets.com; style-src 'self' https://fonts.googleapis.com/; font-src 'self' https://fonts.gstatic.com;"
    X-Content-Type-Options = "nosniff"
