[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' www.datocms-assets.com; font-src fonts.gstatic.com; style-src 'unsafe-inline' fonts.googleapis.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
