[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1"
    Content-Security-Policy: '''
      default-src 'self',
      img-src *,
      style-src *,
      font-src *
    '''
